#!/usr/bin/env bash
# UltraBot - UserBot
# Copyright (C) 2022-2023 UltraBot
#
# This file is a part of < https://github.com/Fahmiiiiiiii/UltraBot/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/Fahmiiiiiiii/UltraBot/blob/main/LICENSE/>.

if [ -d "resources" ]
then
    echo "Current directory Identified.."
else
    apt install git -y
    git clone https://github.com/Fahmiiiiiiii/UltraBot
    cd Ultroid
fi
bash resources/startup/termux.sh
